### ISSUE TITLE
Предложение по моду InediaInfectedAI

### ISSUE THREAD

**Issue by maskitoll11** [ysaroka/InediaInfectedAI#1]
Доброго времени суток! Благодарю за мод это маст хэв! есть предложение сделать для зомби не возможным выбить дверь запертую отмычкой. Это добавит актуальности отмычкам и даст возможность выжить в патовых ситуациях.

**Comment by ysaroka** [comment]
Приветствую.
Такая возможность уже есть, параметр **Zombies.BreakingDoorsOpenLockPickChancePercent**
Это шанс, с которым зомби выбьет дверь, запертую отмычкой. По умолчанию - он равен 5%, что намного меньше, чем шанс выбить не залоченную дверь. Но можно установить и в 0%.
Также есть параметр **Zombies.BreakingDoorsLossInterestAfterHitLockPickChancePercent**, это вероятность, что после удара по двери - зомби потеряет интерес к выбиванию двери, запертой отмычкой и сменить цель внутри сферы (но новая цель выбирается рандомно, так что он может продолжить выбивать дверь, если новая цель за дверью). Аналогичные параметры есть и для двери, которая не заперта отмычкой.

**Comment by maskitoll11** [comment]
ааа и ещё хотел узнать можно или нет прикрутить зомби анимацию взбирания на препятствия от играков? думаю она будет работать намного адекватнее нынешней

**Comment by maskitoll11** [comment]
> Приветствую. Такая возможность уже есть, параметр **Zombies.BreakingDoorsOpenLockPickChancePercent** Это шанс, с которым зомби выбьет дверь, запертую отмычкой. По умолчанию - он равен 5%, что намного меньше, чем шанс выбить не залоченную дверь. Но можно установить и в 0%. Также есть параметр **Zombies.BreakingDoorsLossInterestAfterHitLockPickChancePercent**, это вероятность, что после удара по двери - зомби потеряет интерес к выбиванию двери, запертой отмычкой и сменить цель внутри сферы (но новая цель выбирается рандомно, так что он может продолжить выбивать дверь, если новая цель за дверью). Аналогичные параметры есть и для двери, которая не заперта отмычкой.

ООООО КРУТО!

**Comment by maskitoll11** [comment]
Огромное спасибо за мод! Вы Русско говорящий?

**Comment by ysaroka** [comment]
> ааа и ещё хотел узнать можно или нет прикрутить зомби анимацию взбирания на препятствия от играков? думаю она будет работать намного адекватнее нынешней

Я не особо в этом разбираюсь, но предполагаю, что придется поменять объект каждого зомби в игре, добавив ему эту анимацию. А как быть с модовыми зомби, у которых ее нет.
Короче это совершенно не моя тема.

**Comment by ysaroka** [comment]
> Огромное спасибо за мод! Вы Русско говорящий?

Пожалуйста, да )
Он еще сыроват, как минимум вчера была обнаружена проблема, из-за которой может крашнутся сервер, поэтому не рекомендую использовать там, где это критично, пока не будет выпущено новое обновление.

**Comment by maskitoll11** [comment]
ждите пускай скромного , но доната!)) оч признателен ждал подобного мода со времен первых модов в мастерской!!! ещё раз спасибо!) нарадоваться не могу))
