### ISSUE TITLE
Zombies see fires etc?

### ISSUE THREAD

**Issue by dreamz0r** [ysaroka/InediaInfectedAI#11]
Zombies notices fireplaces and all other attraction (afaik) stuff like roadflares etc through walls and doors.
I entered a house quietly and stayed hidden without attracting them but as soon as the fire was lit they started banging the door down. Doesn't seem right that they will come through from just alittle crackling. 
Im disabling the detection for fireplaces for now but it might need tuning.

**Comment by dreamz0r** [comment]
i mena fireplaces inside static ones in this case, roadflares i get since they project alot of light but fireplaces can soemtimes be closed like the one i tested.

**Comment by ysaroka** [comment]
Zombie sensitivity to road flares can also be adjusted:
https://github.com/ysaroka/InediaInfectedAI/wiki/Description#zombiesreactroadflarevisual

**Comment by dreamz0r** [comment]
Thank you so much for the amount of support you provide and you have obviously thought about it all.
I tried reading the wiki but it was confusing at some points (to me) so i wasnt sure what i could do.

Thank you for answering so clearly!
