### ISSUE TITLE
Conflict with Expansion Quest kill count system

### ISSUE THREAD

**Issue by dreamz0r** [ysaroka/InediaInfectedAI#2]
First of all, the mod is incredible!
Unfortunately when i made a quest to kill zombies the kills won't register on the quest.
All other quests work fine but something makes the zombies not count as kills.
Hope this is fixable because I really want this mod running on my server!

**Comment by ysaroka** [comment]
Hi.
Solution for now - disable damage handlers:
Zombies.DamageToPlayerHandlerIsActive => 0
Zombies.DamageToZombieHandlerIsActive => 0

So far I have not analyzed what exactly the conflict is there, but it will help.

**Comment by dreamz0r** [comment]
This is great, that will make the mod worth to run.
Thank you so much!
Hope you find a solution.

**Comment by ysaroka** [comment]
The issue is fixed, you can return parameters back:
Zombies.DamageToPlayerHandlerIsActive => 1
Zombies.DamageToZombieHandlerIsActive => 1

**Comment by dreamz0r** [comment]
Amazing work, thank you!
