### ISSUE TITLE
Идея: соединение с модом радио

### ISSUE THREAD

**Issue by igorir3** [ysaroka/InediaInfectedAI#24]
Я недавно подружился с начинающим разработчиком FoX, который разрабатывает мод на радио (взамен того, что сделал Yuki). И появилась идея создать какую ни будь систему, что бы зомби из этого мода, как либо реагировали на музыку с радио.

**Comment by ysaroka** [comment]
Реакцию зараженных на любой предмет, который работает через "ComponentEnergyManager" (все ванильные предметы, которые могут включаться/выключаться работают через него) - можно настроить через кастомные раздражители в конфиге:
https://github.com/ysaroka/InediaInfectedAI/wiki/Description#zombiescustomirritants

**Comment by ysaroka** [comment]
По поводу радио Yuki - в модификации добавлялась поддержка автомобильного радио, которое работало не через "ComponentEnergyManager" и вообще никоим образом не было связано с ItemBase, его нельзя было настроить через кастомные раздражители, посему поддержка была встроена в модификацию.
Заодно была добавлена и поддержка обычных приемников, но ничто не мешало настроить эти приемники через кастомные раздражители, и это тоже работало бы.

**Comment by igorir3** [comment]
Проблема ещё в том, что бы "запускать" возбуждение из кода мода (Так как у нас меняется не объект, а его состояние)

**Comment by ysaroka** [comment]
> Проблема ещё в том, что бы "запускать" возбуждение из кода мода (Так как у нас меняется не объект, а его состояние)

А подробнее можно? У вас объект унаследован от ItemBase?
Почему нельзя сделать работу радио через ComponentEnergyManager?
Делать GetCompEM().SwitchOn() при включении и GetCompEM().SwitchOff() при выключении, как было сделано в Yuki?

**Comment by igorir3** [comment]
Короче он сказал, что в ближайшее время не сможет это сделать, (да и сделает ли)
