### ISSUE TITLE
Zombies wont die

### ISSUE THREAD

**Issue by ScAreVex** [ysaroka/InediaInfectedAI#3]
There are some zombies that wont die. If you shoot their legs they will crawl but cant finish them off.  Tried to disable crawling but didnt work , we were still unable to kill the zombies.

**Comment by ysaroka** [comment]
This is conflict with one of your mods that affects damage handler for zombies.
Try disabling damage handler, it should help:
Zombies.DamageToZombieHandlerIsActive => 0

**Comment by ScAreVex** [comment]
Okeyy will try that   thanks for the answer

**Comment by ysaroka** [comment]
Check if the problem remains after today's update.
Naturally, with the parameter enabled:
Zombies.DamageToZombieHandlerIsActive => 1

**Comment by ysaroka** [comment]
Other people have reported that the issue is still present. Apparently this is a conflict with some PvZ parameter, but it is not yet clear which one.
