### ISSUE TITLE
Исчезли предметы в слотах зомби

### ISSUE THREAD

**Issue by AhrenLi78** [ysaroka/InediaInfectedAI#37]
Здраствуйте! Установил ваш мод и мне очень понравилось, сложнилось время выживания на сервере. Но, я заметил у себя одну ошибку, в инфицированых исчезли прописанные предметы. Нету даже тех предметов, которые прописаны на появление 100%. Значит функция обыска тела зомби просто не работает. Если это не так и я ошибаюсь, то направте меня на правильное решение этой проблемы. Просто в некоторых зомби прописаны предметы, которые нужны будут для квестов.
[InediaInfectedAIConfig.json](https://github.com/ysaroka/InediaInfectedAI/files/14735781/InediaInfectedAIConfig.json)

**Comment by ysaroka** [comment]
Мод никак не влияет на предметы в зараженных.
Возможно вы не сделали вайп сервера после установки мода, это может приводить к каким угодно проблемам:
https://github.com/ysaroka/InediaInfectedAI/wiki/FAQ#problems-after-installationserver-fps-drop

**Comment by ysaroka** [comment]
Рекомендую тестировать мод на тестовом сервере, где произведен вайп, а на боевой устанавливать только после планового вайпа.
В скором времени эта проблема судя по всему будет решена и вайп больше не будет обязательным, но на данный момент после установки мода он обязателен.

**Comment by AhrenLi78** [comment]
Вайп был сделан. Предметы именно нету в самих зомби. Они прописаны на появление 100%, но при ОБЫСКЕ трупов зомби, этих вещей нету.

**Comment by ysaroka** [comment]
А если отключить обыск?
```
"Zombies": {
...
    "SearchBodyToViewCargo": {
        "all": 0
     },
 ...
 }
```

Вообще желательно расписать кейс по воспроизведению проблемы:
Какому зомби и каким образом Вы добавляете дроп предмета с 100% шансом (в каком серверном файле и т. д.), если это конечно делается ванильными средствами.
После чего этот предмет не будет появляется в зомби после обыска если мод установлен и будет появляться, если мод не установлен.
Если я повторив эти действия воспроизведу проблему, то она будет подтверждена. Пока что мне ее подтвердить не удается.

**Comment by AhrenLi78** [comment]
При отключении
"Zombies": {
...
    "SearchBodyToViewCargo": {
        "all": 0
     },
 ...
 }
нету кнопки для обыска трупа,. Они просто лежат без всяких функций. 


Файл cfgspawnabletypes  прописан мутант у кого должен появится предмет	
	type name="BRDK_Swampy_crs">
	    cargo preset="grenades" />
		cargo preset="modmixArmy" />
    /type>
	файл cfgrandompresets где прописаны выпадающие предметы, где cargo chance="1" =100%
	cargo chance="1" name="modmixArmy">
		item name="PunchedCard" chance="0.2" />
		item name="TacticalBaconCan" chance="0.1" />
		item name="Canteen" chance="0.1" />
		item name="FS_Mag_PKP_200Rnd" chance="0.2" />
		item name="Ammo_9x19" chance="0.05" />
		item name="FS_Mag_PKP_200Rnd" chance="0.2" />
		item name="AmmoBox_762x39_20Rnd" chance="0.1" />
		item name="Ammo_762x54" chance="0.2" />
		item name="AmmoBox_762x54_20Rnd" chance="0.1" />
		item name="OCP_Auto9" chance="0.1" />
		item name="Mag_Auto9_50Rnd" chance="0.1" />
		item name="Mag_ussrm200_7Rnd" chance="0.1" />
		item name="ER7_Scope" chance="0.05" />
		item name="ER7_Gauss_Magazine" chance="0.05" />
		item name="ER7_Gauss_Battery" chance="0.05" />
		item name="Ammo_ER7RFW" chance="0.05" />
		item name="Mag_bat_Gaus_7rnd" chance="0.05" />
	/cargo>
Больше я незнаю, каким путем можно прописать выпадание предметов в трупе.

**Comment by ysaroka** [comment]
> При отключении
> "Zombies": {
> ...
> "SearchBodyToViewCargo": {
> "all": 0
> },
> ...
> }
> нету кнопки для обыска трупа,. Они просто лежат без всяких функций.

Понятно, что кнопки нет, но лут должен быть виден в зомби если нажать TAB. Отключение этой функции включает ванильный обыск по TAB. Поэтому я и пытаюсь понять, влияет сама функция обыска в вашем случае либо что-то другое.

**Comment by AhrenLi78** [comment]
Сейчас ещё раз попробую с отключеной функцией обыска

**Comment by ysaroka** [comment]
У вас chance="1", т. е. 100% стоит **для пресета**, а в самом пресете для предметов шансы стоят от 5% до 20%.
При таких настройках не всегда будет что-то выпадать.
Поставьте для какой-нибудь PunchedCard шанс 100%, чтобы быть уверенным, что эта Card точно выпадет:
`<item name="PunchedCard" chance="1" />`

**Comment by ysaroka** [comment]
Для теста сделал следующее, для пресета foodCity, который привязан к городским зараженным, в файле cfgrandompresets.xml поменял шанс для SodaCan_Cola и самого пресета на 100%:
```
		<cargo chance="1" name="foodCity"> <!--same as the one above - just preparing -->
				<item name="SodaCan_Cola" chance="1" />
				<item name="SodaCan_Pipsi" chance="0.02" />
				<item name="SodaCan_Spite" chance="0.02" />
				<item name="SodaCan_Kvass" chance="0.02" />
				<item name="SodaCan_Fronta" chance="0.02" />
				<item name="WaterBottle" chance="0.02" />
				<item name="TunaCan" chance="0.05" />
				<item name="SardinesCan" chance="0.05" />
				<item name="PeachesCan" chance="0.05" />
				<item name="SpaghettiCan" chance="0.05" />
				<item name="BakedBeansCan" chance="0.05" />
				<item name="PowderedMilk" chance="0.05" />
				<item name="Pajka" chance="0.05" />
				<item name="Pate" chance="0.05" />
				<item name="BrisketSpread" chance="0.05" />
				<item name="SaltySticks" chance="0.05" />
				<item name="Crackers" chance="0.05" />
				<item name="Chips" chance="0.05" />
		</cargo>
```
После этого - из городских зараженных всегда с 100% шансом выпадает SodaCan_Cola и иногда другие предметы вместе с ней.
И функция обыска на это никак не влияет, да и не должна влиять, так как всё, что она делает - это делает видимым лут в зараженном и никак не влияет на сам лут, его количество и шанс.

**Comment by AhrenLi78** [comment]
![Изображение WhatsApp 2024-03-24 в 20 08 23_14aaf880](https://github.com/ysaroka/InediaInfectedAI/assets/153004111/8536d635-9d33-497d-a24c-96675f30a21b)
![Изображение WhatsApp 2024-03-24 в 20 09 03_1b4b40a9](https://github.com/ysaroka/InediaInfectedAI/assets/153004111/3280e474-4541-419b-939b-01c16e5401aa)
Перебил кучу зомби.... Чтук на 30, ни в одном нету предмета, хотя в каждом зомби должна выпадать валюта игровая, спавнил BRDK_Swampy_crs 3 раза, и бил рандомных BRDK_Swampy_crs на местах их дислокаций, ни в одной не выпало предмета. Обыск при этом был отключен....  
cargo chance="1" = 100% и какой либо предмет должен с этой вероятностью выпадать.
Вы не можите мне выслать свой файл конфигурации, и если я его подменю, будет работать это всё?
 Varne2007@yandex.ru  Благодарю за помощ

**Comment by ysaroka** [comment]
Ну т. е. функция обыска на это не влияет, а влияет что-то другое.
Возможно, это конфликт с каким-то из ваших модов.
Отключите InediaInfectedAI и проверьте вообще без него, будет ли работать.

Файл конфигурации дефолтный:
https://github.com/ysaroka/InediaInfectedAI/wiki/Default-configuration-file
Но конфигурация на это вообще никак не влияет, потому что InediaInfectedAI не влияет на выпадаемые предметы и в нем нет параметров для настройки этого.

**Comment by AhrenLi78** [comment]
будем думать и искать проблему. Отпишусь, как всё получится.

**Comment by AhrenLi78** [comment]
Вроде пока работает всё. Последующие мои действия:
Ошибка моя была наверно в том, что я сразу начинал редактировать файл. Несколько раз я просто подменял файл ранне отредактированым и возможно мод не воспринимал их.
Пробовал ставил файл https://github.com/ysaroka/InediaInfectedAI/wiki/Default-configuration-file  , но почему то лут в мобах не появлялся.
Первое что я сделал - это удалил файл из папки Inedia, запустил сервер. Мод сам сгенирировал файл, после чего в игре появились предметы в зомбиках. 
Выключил сервер, прописал ИД админа, запустил сервер. Всё работает, потом так же перезапустил, только уже с выключиным параметром 
"BreakingDoorsHandlerIsActive": {
            "all": 0
так как мне не нужно открытие дверей. Зашёл в игру, всё нормально, лут появляется.... 
Больше пока в файле ни чего не меняю, так как боюсь, вдруг откажет =) .

**Comment by ysaroka** [comment]
Конфиг мода на это никак не влияет и не может влиять, тут в чем-то другом дело было. Возможно, cfgrandompresets.xml не обновлялся по какой-то причине а перегенерация конфига вызвала это обновление.

Касательно "Zombies.BreakingDoorsHandlerIsActive".
Его нужно отключать только если другой мод обрабатывает выбивание дверей, само выбивание дверей отключается другими параметрами. Если отключать этим - они будут застревать в дверях.
Все описано в описании самого параметра:
https://github.com/ysaroka/InediaInfectedAI/wiki/Description#zombiesbreakingdoorshandlerisactive
