### ISSUE TITLE
DayZ v1.26 : action issue to your mods (DayZ code change)

### ISSUE THREAD

**Issue by stephanepapin** [ysaroka/InediaInfectedAI#45]
Hi John

Please check your mod with v1.26, reported by many player : after any action with environment, players must logout/login to be able to interact with environment.

Example
**Before : ** 
```
void SPA_ActionDestroyCarWreck()
    {
        m_CallbackClass        = SPA_ActionDestroyCarWreckCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONFB_DISASSEMBLE;
        m_FullBody            = true;
        m_StanceMask        = DayZPlayerConstants.STANCEMASK_ERECT;
    }
```
--> Players are stuck

**After :**
```
void SPA_ActionDestroyCarWreck()
    {
        m_CallbackClass        = SPA_ActionDestroyCarWreckCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONFB_DISASSEMBLE;
        m_FullBody            = true;
        m_StanceMask        = DayZPlayerConstants.STANCEMASK_ERECT;
        m_LockTargetOnUse     = false;
    }
```
You must add `m_LockTargetOnUse     = false;` to all actions in code
--> Players no longer are stuck

It's a change in DayZ code.

Regard

**Comment by ysaroka** [comment]
Any issues with specific actions?
For the actions of quietly opening and closing doors, I have made the following changes:
```
	override bool IsLockTargetOnUse()
	{
		return false;
	}
```

There didn’t seem to be any issues with the action of searching the infected either, but I’ll check again.
