### ISSUE TITLE
"ReactBodyfallDayNoise" does not seem to be working for me

### ISSUE THREAD

**Issue by icSlowMo** [ysaroka/InediaInfectedAI#47]
I have it set to this,

"ReactBodyfallDayNoise": {
            "all": 1.0
        },
        
 and with a VSS, I can head shot a zombie from a distance and Zeds go to where the bullet impacts, not to where the body falls. Map is Sakhal.
 
 May need to add a weather (Rain/snow) reactive adjustment as well.

**Comment by icSlowMo** [comment]
My file,

[InediaInfectedAIConfig.json](https://github.com/user-attachments/files/17470182/InediaInfectedAIConfig.json)

Ok today, seems to be working a little better.. not sure what was going on yesterday.... I was able to set the value higher then 1.0 before recent updates though....

**Comment by ysaroka** [comment]
For _React*_ parameters (except for _Zombies.ReactVanillaMindstateChange_), it is not possible to set a value higher than 1, this has always been the case, and it is also mentioned in the description of the parameters themselves.

That is, the maximum radius of effect of this irritant is 30 meters from the falling body.

**Comment by ysaroka** [comment]
Also, it's important to remember that if a zombie has reacted to a body fall once, it will not react to the same irritant for the next 4-8 minutes. This is done to prevent abuses related to constantly irritating zombies from a distance using a suppressed weapon.

**Comment by icSlowMo** [comment]
Yep, I did read all that... But it seems to be working today, idk why it wasn't working yesterday even after several server restarts. They don't seem as sensitive as they used to be for some reason though... But thanks for the reply. And Love the mod. 👍
