### ISSUE TITLE
butchering 

### ISSUE THREAD

**Issue by evillindsey** [ysaroka/InediaInfectedAI#49]
i have butchering turned off, i run a hard core server, butchering makes it easy to get rope and fish, it is turned to off but i can still do it., making it easy for my players. i have completely deleted the file wiped the server, started again and still no joy, it was fine before the 1.26 update (always leave it for an update to break something) 
[InediaInfectedAIConfig.json](https://github.com/user-attachments/files/17531146/InediaInfectedAIConfig.json)

**Comment by ysaroka** [comment]
I checked your config, everything is working fine, and butchering is disabled. It's likely that one of your mods is adding this mechanic.

**Comment by evillindsey** [comment]
i did look at that to but i dont see a mod that would, tbh but i will look again

**Comment by evillindsey** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=3077143744&searchtext= i found the mod conflict i know the Modder so he is changing it for me sent you it so you know in case of future conflicts

**Comment by ysaroka** [comment]
This mod simply enables butchering for all infected on the server, apparently, it needs this for some reason.

**Comment by evillindsey** [comment]
he took it off so its not doing it
