### ISSUE TITLE
Suggestion: change sounds for door banging on metal doors to something lower pitch

### ISSUE THREAD

**Issue by dreamz0r** [ysaroka/InediaInfectedAI#5]
The sound for zombies banging on metal doors is way too high pitched, would be better with a lower pitch *donk* imo.
Noticed it on garages and containers.

Absolutely amazing mod and i look forward to see what the future brings.

**Comment by ysaroka** [comment]
Probably yes, but I'll have to look for suitable free audio. If you have options, I'm ready to listen.

**Comment by dreamz0r** [comment]
I have a friend I can ask that does sfx, maybe he's willing to do one or two if I ask very nicely.

**Comment by ysaroka** [comment]
It would be great. If there are several sounds, I will launch them randomly.

**Comment by ysaroka** [comment]
The sound of knocking on a metal door has been changed to a lower pitch.
