### ISSUE TITLE
Проблема с ключом

### ISSUE THREAD

**Issue by igorir3** [ysaroka/InediaInfectedAI#7]
Переименую папку key в keys
А то, я сделал лаунчер для сервера, и твой мод единственный, что наименовал папку key.
Тем более так удобнее при ручном вводе ключей потому, что лучше просто перенести папку на каталог выше, нежели перемещать сам файл!

**Comment by ysaroka** [comment]
Ок, в следующем апдейте переименую.

**Comment by ysaroka** [comment]
С сегодняшним апдейтом директория переименована в "keys".
